### ISSUE TITLE
Is it possible to use this library in a Bluetooth mesh gateway and control Bluetooth mesh nodes through Adv beares?

### ISSUE THREAD

**Issue by RAlexeev** [SilvairGit/python-bluetooth-mesh#157]
Hi!
Could you clarify a bit, does this library allow to control Bluetooth mesh devices directly, using Adv bearers, or does it use GATT bearers through an intermediate Bluetooth mesh node with Proxy feature to communicate with Bluetooth mesh nodes? It seems that BlueZ supports only provisioning and not controlling Bluetooth mesh network. I would like to understand whether it's possible to control Bluetooth mesh network directly from Linux (Raspberry Pi) without any intermediate MCU with Bluetooth mesh support.
It seems that nRF Mesh mobile app from Nordic employes a specific opportunity to control devices via PB-GATT packet, connecting to a Bluetooth mesh node with Proxy feature. A mobile device connects to the node using Bluetooth LE and encapsulates Bluetooth mesh packets, sending through this node, and not directrly, using Bluetooth mesh advertising packets. So, could you clarify, is it possible to control Bluetooth mesh networks from Linux using your library?

**Comment by michallowasrzechonek-silvair** [comment]
BlueZ uses adv bearer only. This library is just an interface to bluetooth-meshd.

**Comment by RAlexeev** [comment]
Many thanks for your reply! Could you clarify a bit, does this library (bluetooth-meshd) allow us to create a BLE mesh node using merely Raspberry PI and control BLE mesh network from it?

**Comment by michallowasrzechonek-silvair** [comment]
Yes, it does.

**Comment by RAlexeev** [comment]
Sounds great! Thanks!
So is your library a convenient wrapper for bluetooth-meshd? Does bluetooth-meshd itself provide the feature for Raspberry Pi with Linux (BlueZ) to be a complete fully functional BLE mesh node?

**Comment by michallowasrzechonek-silvair** [comment]
That is correct.

**Comment by RAlexeev** [comment]
Great news! Thank you! After your experience of using BlueZ library for BLE mesh network, could you estimate how the library (specifically bluetooth-meshd) is mature nowadays to use it in production? Since your wrapper based on it, its appicability directly depends on this base library for Bluetooth mesh controlling. And also, could you reveal how complete your library (python-bluetooth-mesh) supports all the BLE mesh features?

**Comment by michallowasrzechonek-silvair** [comment]
It works for us, but YMMV. It's open source, neither us nor bluez maintainers guarantee anything.
