### ISSUE TITLE
Any example code for provisioning and messaging?

### ISSUE THREAD

**Issue by RobLut** [SilvairGit/python-bluetooth-mesh#20]
Hello,

I'm interested in experimenting with your code in a wireless mesh project that I am workin on.  Do you have any example code (provisioning, interaction with lights/switches or just generic on/off) that you could add to the repo?

Thank you,

Shane

**Comment by mrzechonek** [comment]
I would recommend taking a look at https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mesh-api.txt

This repo contains a very rudimentary (and unmaintained) GATT proxy client only. If you want to play with it, I suggest looking at https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt

**Comment by mrzechonek** [comment]
Also, at the moment we maintain only the codes for messages.

**Comment by michallowasrzechonek-silvair** [comment]
@RobLut you might want to take a look at `meshcli` utility.

At the moment it's coupled with Silvair Commissioning Platform, but that's about to change - I'd like the basic functionality to be available in standalone mode.

Anyway, code in 'models' demonsrates messaging, and 'meshcli' shows high-level usage.

There is also some rudimentary documentation available now.
