### ISSUE TITLE
Config Client add_publication: no subconstruct matched

### ISSUE THREAD

**Issue by e-va** [SilvairGit/python-bluetooth-mesh#34]
Hi,

I'm trying to provision a node via PB-ADV. When I set the publication address of my vendor model I get a timeout followed by this:

```
Traceback (most recent call last):
  File "main.py", line 313, in <module>
    main()
  File "main.py", line 309, in main
    loop.run_until_complete(app.run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "main.py", line 282, in run
    MyVendorModel)
  File "/home/venv_python/lib/python3.7/site-packages/bluetooth_mesh/models/models.py", line 697, in add_publication
    status = await self.query(request, status, send_interval=0.2, timeout=4)
  File "/home/venv_python/lib/python3.7/site-packages/bluetooth_mesh/models/base.py", line 379, in query
    await sender
  File "/home/venv_python/lib/python3.7/site-packages/bluetooth_mesh/models/base.py", line 369, in sender
    await request()
  File "/home/venv_python/lib/python3.7/site-packages/bluetooth_mesh/models/base.py", line 314, in send_dev
    data = AccessMessage.build(dict(opcode=opcode, params=params))
  File "/home/venv_python/lib/python3.7/site-packages/construct/core.py", line 352, in build
    self.build_stream(obj, stream, **contextkw)
  File "/home/venv_python/lib/python3.7/site-packages/construct/core.py", line 364, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/home/venv_python/lib/python3.7/site-packages/construct/core.py", line 3500, in _build
    raise SelectError("no subconstruct matched: %s" % (obj,))

construct.core.SelectError: no subconstruct matched: {'opcode': <ConfigOpcode.MODEL_PUBLICATION_SET: 3>, 
'params': {'element_address': 170, 'publish_address': 49154, 'TTL': 8, 'app_key_index': 0, 
'credential_flag': <PublishFriendshipCredentialsFlag.MASTER_SECURITY: 0>, 'RFU': 0, 
'publish_period': {'step_resolution': 2, 'number_of_steps': 6}, 'retransmit': {'interval_steps': 0, 'count': 2}, 
'model': {'vendor_id': 767, 'model_id': 43981}}}
```

I'm using Python 3.7.5 with package version 0.2.3.  Setting netkey, appkey, binding the appkey and adding the subscription for my vendor model works fine (with occasional timeouts). Also, I've successfully provisioned my node (including `pub-set 00aa c002 0 0 0 abcd 02ff`) using bluez mesh-cfgclient. 

Could you give me a hint what this error means and what I'm doing wrong?

Thanks & best regards

ps: the method call and the model
```
target = 0x00aa 
await client.add_publication(target, net_index, target, 
    MY_VENDOR_MODEL_ADDR, app_key_index, MyVendorModel)


# MY VENDOR MODEL
MY_VENDOR_MODEL_ID = 0xabcd
MY_VENDOR_MODEL_ADDR = 0xc002


class MyVendorModelOpcode(IntEnum):
    POST_DATA = 0x0001,
    START_ADVERTISING = 0x0002,
    STOP_ADVERTISING = 0x0003


class MyVendorModel(Model):
    MODEL_ID = (VENDOR_ID, MY_VENDOR_MODEL_ID)
    OPCODES = [
        MyVendorModelOpcode.POST_DATA,
        MyVendorModelOpcode.START_ADVERTISING,
        MyVendorModelOpcode.STOP_ADVERTISING
    ]
```

**Comment by michallowasrzechonek-silvair** [comment]
Thanks for the report.

I think this is a bug - we've recently added a more human-friendly API for retransmission fields: https://github.com/SilvairGit/python-bluetooth-mesh/blob/master/bluetooth_mesh/messages/config.py#L562-L585, but it seems we forgot to actually use it in `ConfigClient`.

Could you please try changing `interval_steps` to just `interval` (in milliseconds) in function `ConfigModel.add_publication`? Relevant lines are:

https://github.com/SilvairGit/python-bluetooth-mesh/blob/master/bluetooth_mesh/models/models.py#L671
https://github.com/SilvairGit/python-bluetooth-mesh/blob/master/bluetooth_mesh/models/models.py#L692

**Comment by e-va** [comment]
Thanks for the quick response.
I made the replacements. Unfortunately that did not solve the problem.

```
File "/home/venv_python/lib/python3.7/site-packages/construct/core.py", line 3500, in _build
    raise SelectError("no subconstruct matched: %s" % (obj,))
construct.core.SelectError: no subconstruct matched: {'opcode': <ConfigOpcode.MODEL_PUBLICATION_SET: 3>, 
'params': {'element_address': 170, 'publish_address': 49154, 'TTL': 8, 'app_key_index': 0, 
'credential_flag': <PublishFriendshipCredentialsFlag.MASTER_SECURITY: 0>, 'RFU': 0, 
'publish_period': {'step_resolution': 2, 'number_of_steps': 6}, 'retransmit': {'interval': 0, 'count': 2}, 
'model': {'vendor_id': 767, 'model_id': 43981}}}
```

**Comment by rafalgajda-silvair** [comment]
Hi, 
Thanks for taking interest in this project. I pushed a patch that should fix the problem in `ConfigClient.add_publication()` method.

Please note that retransmit interval cannot be 0 as it now is an actual time value in milliseconds. 
It should be a value in range `10-320ms` in `10ms` intervals for Network and Relay retransmissions and `50-1600ms` in `50ms` intervals for Publications.

I added checks to make sure error reporting is more verbose.

**Comment by e-va** [comment]
Wow, thanks a lot for the quick patch! That did fix the problem. :D
I also assigned the retransmit interval a valid value, thanks for the hint.
