### ISSUE TITLE
Problem initializing an instance of a subclass of Application

### ISSUE THREAD

**Issue by sbrown4** [SilvairGit/python-bluetooth-mesh#44]
The call to dbus_connect() wasn't being made when I created an instance of Application per skeleton.py. It looks like `__aenter__` needs to be called for that to occur. So, creating the instance has to be in an `async with`. But, `__aenter__` doesn't return the instance, which I think it should.

 ```
async def __aenter__(self):
    await self.dbus_connect()
    return self
```
Returning the instance seemed to fix things for me.
This is my first attempt to use this package, So, this may just be a misunderstanding.

**Comment by lukaszdudek-silvair** [comment]
HI!

The idea of the current API is that you should first construct an instance & then use it as a context manager:
```python
app = SampleApp(loop)
async with app:
    await app.run()
```

It seems that the example in `skeleton.py` is outdated - we'll fix it. You're right, though, that returning `self` from `__aenter__` would enable a simpler usage of the API.
