### ISSUE TITLE
Do I need to install the Bluez stack before using this library?

### ISSUE THREAD

**Issue by tcexeexe** [SilvairGit/python-bluetooth-mesh#68]
As the title,and which versions of bluez is latest supported?

**Comment by michallowasrzechonek-silvair** [comment]
Yes, and ideally you need the "latest master" from git, mesh API isn't considered stable yet.

**Comment by tcexeexe** [comment]
ok.
But l try to use "pip3 install python-bluetooth-mesh" to install ,but an error happened :
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.tuna.tsinghua.edu.cn/simple/python-bluetooth-mesh/
the python version is 3.7.3, hardware is raspberry 3B+ , is there any Suggestions that can help me solve this problem?
![image](https://user-images.githubusercontent.com/28287196/95011336-961d5b00-0662-11eb-8f9c-9db324b0ec1c.png)

**Comment by michallowasrzechonek-silvair** [comment]
It's called "bluetooth-mesh" on pypi.
