### ISSUE TITLE
Do we have any documentation?

### ISSUE THREAD

**Issue by santhosh12992** [SilvairGit/python-bluetooth-mesh#86]
Hello,

I am new to mesh and trying to get my hands on. I am having a standard sigma mesh light bulb and linux bluez. Is there any documentation available in meshcli.py usage?

Thanks.

**Comment by michallowasrzechonek-silvair** [comment]
Nope. A the moment it's just "use the code, Luke". Sorry.

We have rudimentary API documentation at https://python-bluetooth-mesh.readthedocs.io/en/latest/?badge=latest but that's it.
